Fixed o_full error in fifo code and altered some syntax properties.
ColinFritzLtts/CAN_Controller pull request #46
Opened 2020-07-30 18:57 UTC by boomshakakan

errors in fifo should be fixed and all code should adhere to updated requirements.

2020-07-30 19:18 UTC, Nemiland requested changes
See code comment @line 99

2020-07-30 19:18 UTC, Nemiland commented on Source_Code/FIFO/can_fifo.sv
> +                        ptr_sub = 1'b1;
shouldn't this also have the read pointer advancement?

2020-07-30 22:20 UTC, boomshakakan commented on Source_Code/FIFO/can_fifo.sv
> +                        ptr_sub = 1'b1;
I see what you are saying. I pushed fix now.

2020-07-31 16:35 UTC, Nemiland approved these changes

2020-07-31 16:35 UTC, merged